package com.nothing.messenger.theme.color_palettes

import androidx.compose.ui.graphics.Color
import com.nothing.messenger.theme.MaterialThemeColorsPalette

object BlueColorBase : MaterialThemeColorsPalette {
    override val primaryLight: Color = Color(0xFF1473FF)
    override val onPrimaryLight: Color = Color(0xFFFFFFFF)
    override val primaryContainerLight: Color = Color(0xFFD1E4FF)
    override val onPrimaryContainerLight: Color = Color(0xFF001D36)
    override val secondaryLight: Color = Color(0xFF545F71)
    override val onSecondaryLight: Color = Color(0xFFFFFFFF)
    override val secondaryContainerLight: Color = Color(0xFFD8E2FF)
    override val onSecondaryContainerLight: Color = Color(0xFF0D1B30)
    override val tertiaryLight: Color = Color(0xFF6B5778)
    override val onTertiaryLight: Color = Color(0xFFFFFFFF)
    override val tertiaryContainerLight: Color = Color(0xFFEEDBFF)
    override val onTertiaryContainerLight: Color = Color(0xFF29132D)
    override val errorLight: Color = Color(0xFFBA1A1A)
    override val onErrorLight: Color = Color(0xFFFFFFFF)
    override val errorContainerLight: Color = Color(0xFFFFDAD6)
    override val onErrorContainerLight: Color = Color(0xFF410002)
    override val backgroundLight: Color = Color(0xFFFDFCFF)
    override val onBackgroundLight: Color = Color(0xFF1A1C1E)
    override val surfaceLight: Color = Color(0xFFFDFCFF)
    override val onSurfaceLight: Color = Color(0xFF1A1C1E)
    override val surfaceVariantLight: Color = Color(0xFFE0E2EC)
    override val onSurfaceVariantLight: Color = Color(0xFF44474E)
    override val outlineLight: Color = Color(0xFF74777F)
    override val outlineVariantLight: Color = Color(0xFFC4C6D0)
    override val scrimLight: Color = Color(0xFF000000)
    override val inverseSurfaceLight: Color = Color(0xFF2F3133)
    override val inverseOnSurfaceLight: Color = Color(0xFFF1F0F4)
    override val inversePrimaryLight: Color = Color(0xFF9FC1FF)
    override val surfaceDimLight: Color = Color(0xFFDCE0EA)
    override val surfaceBrightLight: Color = Color(0xFFFDFCFF)
    override val surfaceContainerLowestLight: Color = Color(0xFFFFFFFF)
    override val surfaceContainerLowLight: Color = Color(0xFFF6F7FA)
    override val surfaceContainerLight: Color = Color(0xFFEFF1F5)
    override val surfaceContainerHighLight: Color = Color(0xFFE9EBEF)
    override val surfaceContainerHighestLight: Color = Color(0xFFE3E5EA)

    override val primaryDark: Color = Color(0xFF9FC1FF)
    override val onPrimaryDark: Color = Color(0xFF00325A)
    override val primaryContainerDark: Color = Color(0xFF00488D)
    override val onPrimaryContainerDark: Color = Color(0xFFD1E4FF)
    override val secondaryDark: Color = Color(0xFFBBC7DA)
    override val onSecondaryDark: Color = Color(0xFF233044)
    override val secondaryContainerDark: Color = Color(0xFF3A485D)
    override val onSecondaryContainerDark: Color = Color(0xFFD8E2FF)
    override val tertiaryDark: Color = Color(0xFFD5BEEA)
    override val onTertiaryDark: Color = Color(0xFF3F284D)
    override val tertiaryContainerDark: Color = Color(0xFF553D63)
    override val onTertiaryContainerDark: Color = Color(0xFFEEDBFF)
    override val errorDark: Color = Color(0xFFFFB4AB)
    override val onErrorDark: Color = Color(0xFF690005)
    override val errorContainerDark: Color = Color(0xFF93000A)
    override val onErrorContainerDark: Color = Color(0xFFFFDAD6)
    override val backgroundDark: Color = Color(0xFF121316)
    override val onBackgroundDark: Color = Color(0xFFE2E3E7)
    override val surfaceDark: Color = Color(0xFF121316)
    override val onSurfaceDark: Color = Color(0xFFE2E3E7)
    override val surfaceVariantDark: Color = Color(0xFF44474E)
    override val onSurfaceVariantDark: Color = Color(0xFFC4C6D0)
    override val outlineDark: Color = Color(0xFF8D9099)
    override val outlineVariantDark: Color = Color(0xFF44474E)
    override val scrimDark: Color = Color(0xFF000000)
    override val inverseSurfaceDark: Color = Color(0xFFE2E3E7)
    override val inverseOnSurfaceDark: Color = Color(0xFF2F3133)
    override val inversePrimaryDark: Color = Color(0xFF1473FF)
    override val surfaceDimDark: Color = Color(0xFF121316)
    override val surfaceBrightDark: Color = Color(0xFF383A42)
    override val surfaceContainerLowestDark: Color = Color(0xFF0C0E10)
    override val surfaceContainerLowDark: Color = Color(0xFF1A1C1F)
    override val surfaceContainerDark: Color = Color(0xFF1E2024)
    override val surfaceContainerHighDark: Color = Color(0xFF282B30)
    override val surfaceContainerHighestDark: Color = Color(0xFF33363C)
}
